name: "Cloudflare DNS"
description: "Updates Cloudflare A Records To Public IP"
version: "1.0.0"
slug: "cloudflare_dns"
init: false
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
options:
    token: ""
    zone: ""
    records: ""
    schedule: "0 * * * *"
schema:
    token: "str"
    zone: "str"
    records: "str"
    schedule: "str?"
